[theme]
primaryColor="#3498db"
backgroundColor="#2c3e50"
secondaryBackgroundColor="#34495e"
textColor="#ffffff"
font="sans serif"
[server]
enableCORS = true
corsAllowedOrigins = ['http://localhost:8501', 'https://opopmm.streamlit.app/', 'https://boe.es']